# Generated by Django 3.0.2 on 2020-01-25 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Breaks',
            new_name='Break',
        ),
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
        migrations.RenameModel(
            old_name='Shifts',
            new_name='Shift',
        ),
    ]
