# Generated by Django 3.0.2 on 2020-01-25 23:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20200125_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='break',
            name='return_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='break',
            name='shift',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Shift'),
            preserve_default=False,
        ),
    ]
