# Generated by Django 3.0.2 on 2020-01-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20200125_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='status',
            field=models.CharField(choices=[('H', 'Present'), ('C', 'Call Off'), ('N', 'No Call No Show'), ('L', 'Late'), ('E', 'Left Early'), ('M', 'Medical'), ('Z', 'Not Here Yet')], default='Z', max_length=1),
        ),
    ]
