# Generated by Django 3.0.2 on 2020-01-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_shift_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='reason',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
