# Generated by Django 3.0.2 on 2020-01-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_shift_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='break',
            name='return_time',
            field=models.TimeField(blank=True),
        ),
    ]
