# Generated by Django 3.0.2 on 2020-01-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20200125_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='break',
            name='is_lunch',
            field=models.BooleanField(default=False),
        ),
    ]
