# Generated by Django 3.0.2 on 2020-01-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_break_is_lunch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1024)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-date']},
        ),
    ]
