# Generated by Django 3.0.2 on 2020-01-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_auto_20200127_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='break',
            name='on_break',
            field=models.BooleanField(default=False),
        ),
    ]
