# Generated by Django 3.0.2 on 2020-01-29 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_break_on_break'),
    ]

    operations = [
        migrations.AddField(
            model_name='break',
            name='scheduled_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
