# Generated by Django 3.0.2 on 2020-01-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_break_scheduled_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='break',
            name='break_time',
            field=models.TimeField(blank=True),
        ),
    ]
